### ISSUE TITLE
Turbo Mode for JRuby

### ISSUE THREAD

**Issue by Kavignon** [celluloid/GSoC#1]
Hi,

Yes I know the GSoC program has started. I was wondering if this project could be something I could work off the book on my own personal time this year. I also wanted to know, except what was mentioned, are there other things you could direct me to in order to fully implement this? I have experience with Java but none in Ruby. This will be a fun experience in order to learn.

**Comment by digitalextremist** [comment]
@Kavignon you are always welcome to make `F/OSS` contributions, without being in `GSoC`. But if you need a mentor on this project, check out the `Ruby Language` organization:
- https://summerofcode.withgoogle.com/organizations/5749695703941120/

This organization is focused on `Celluloid` only.

**Comment by tarcieri** [comment]
@digitalextremist I think he was asking about a JRuby-optimized backend for Celluloid. Nowadays that'd probably just involve leveraging the proper `concurrent-ruby` primitives.
